name: Cyrpess Tests

on: [push, repository_dispatch]

jobs:
  cypress-run:
    runs-on: ubuntu-16.04
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          env: confluence_password=46ZMPy42Dnm6sGNW,confluence_username=jack.sandeman,aws_access_key_id=AKIARJLWD3FYMMWLZ7MQ,aws_secret_access_key=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
          start: npm run start-server
          wait-on: 'http://localhost:3000'