name: Cyrpess Tests

on: [push, repository_dispatch]

jobs:
  cypress-run:
    runs-on: ubuntu-16.04
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Cypress run
        uses: cypress-io/github-action@v2
        env:
          confluence_password: ${{ secrets.CONFLUENCE_PASSWORD }}
          confluence_username: ${{ secrets.CONFLUENCE_USERNAME }}
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        with:
          start: npm start
          wait-on: 'http://localhost:3000'